# Generated by Django 5.2.2 on 2025-06-07 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pshelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stats', models.CharField(choices=[('student', 'Student'), ('professional', 'Professional')], max_length=20)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_image', models.URLField()),
                ('project_link', models.URLField()),
                ('project_date', models.DateField()),
                ('project_technologies', models.CharField(max_length=200)),
                ('project_outcomes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
